### PR TITLE
iOSAssessment - Alexey Kalentiev

### PR DESCRIPTION
**Pull request by heach**
<b>Dear Suitsupply team!</b>

Please review my solution for your iOS Assessment task. 
Let me please explain main features of this small application.

This is a application with architecture similar to XCode MasterDetails template. Application is universal and created for iOS 8.0 and greater.
On the first screen there is a tableview with the list of some products. Application sending request to BestBuy API and then reloading table, when user scrolled to down, data source sending request for  next page of products. User can select category to load by pressing "Action" button at the left side of navigation bar. By pressing it, categories list opens, and user can select one category or clear selection.  
On the main screen user can select row and then product details view is displaying. On the view there is a poster of product, additional info and also two buttons for loading related and accessory products as described in task.

<b>Third party libraries reference:</b>
I’m using:

1. AFNetworking to make API calls. In this project AFNetworking is too heavy, but in general I prefer to use AFNetworking because of possibility to work with request as NSOperationQueue, for easy downloads/uploads. Also AFNetworking provide good interface to interact with web services. 

2. Mantle to map JSON into Objective-C objects. It’s easy to create model layer and parameters with help of Mantle. 

3. SDWebImage to cache images. Again, I’m using a sledge-hammer to crack a nut, but AFNetworking image cache is broken since iOS8, so I replaced it with SDWebImage for a while.

4. libextobjc for KVO and variables in blocks. It provides easier and cleaner way of weakifying variables.

5. APParallaxHeader to create nice product details view. 

<b>Known issues:</b>

1. Application not handling API errors correctly.
2. Application not tested on big amounts of data. 
3. No Unit testing.

Best regards,
Alexey Kalentiev

### CODE REVIEW

**Comment by JaviLorbada** [comment]
Hi Alexey,

Thank you so much for your time doing the assessment, hope you had fun. The Suitsupply Mobile Team has reviewed the PR and we have commented some code inline, but we also have some global questions.

* There's an issue at the `SSACategoriesSelectTableViewController`, when the view has loaded more categories and the user presses on any of them the table view starts scrolling up, you can see the issue in the following video.

categoriesissue

Would it be possible to solve this issue and PR again?

* At the [`SSASearchProductsTableViewController`](https://github.com/heach/iOSAssessment/blob/master/iOSAssessment/Controllers/SearchProducts/SSASearchProductsTableViewController.m#L108), when the user refreshes the list of products by using the "Pull to refresh" the screen goes blank. Why is that happening? Why does the ActivityIndicator on the "Pull to refresh" stop before the products have loaded?

You can see the issue in the following video. 

blankscreen

Would it be possible to solve this issue and PR again?

* We would liked you to use more micro commits, in that way it would have been easier to review your code, is there any reason why you've use the current number of commits?

* We liked you've used branches, but is there a reason why they are still there? See: https://github.com/heach/iOSAssessment/branches/active

Again, thank you so much for your time, and we are looking forward to hear from you.

Cheers,

Javi on behalf of the Suitsupply Mobile Team.

**Comment by heach** [comment]
Hello Javi,

Thanks a lot for your comments.
I will fix all issues as soon as possible. Also will update my solution due to your comments, I have few new thoughts now.

Sure, I will commit more frequently. This is no reason why I'm using current number of commits.
What about branches, I will delete them, i just wanted to show, that I familiar with Vincent Driessen's branching model.

Best regards,
Alexey Kalentiev

**Comment by JaviLorbada** [comment]
Thanks for your quick answer! We are looking forward to see your new solution 🙌

**Comment by heach** [comment]
Hello @JaviLorbada !

I found the reason of tableview scrolling to the top:

>There's an issue at the `SSACategoriesSelectTableViewController`, when the view has loaded more categories and the user presses on any of them the table view starts scrolling up, you can see the issue in the following video.

Maybe you would found this information useful. This issue is known bug of iOS 8 self sizing cells. Please see [this stackoverflow question](http://stackoverflow.com/questions/25937827/table-view-cells-jump-when-selected-on-ios-8). Removing TableView reloading when user select category, that you kindly pointed in your comment, solved this issue for me.

**Comment by heach** [comment]
I updated my solution, and pushed changes to master branch. 

There is a list of changes:

* Fixed refresh controll
* Fix to prevent tableview from scrolling to the top on category selection.
* Added proper rotation handling
* Product displaying fixes. (tableview top space, price displaying)
* Unified datasource and controller for product list table views.

Again thanks a lot for your comments. Looking forward to hearing from you!

Have a nice day! :)

**Comment by JaviLorbada** [comment]
Thanks for the great Work Alexey! ✨

We will get back to you soon.

**Pull request closed without merging**
